name: news_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #상태관리
  flutter_bloc: ^8.1.2

  #클래스 비교
  equatable: ^2.0.5

  #의존성 주입
  get_it: ^7.6.0

  #dateFormat
  intl: ^0.18.1

  #persistence library
  floor: ^1.4.2

  #요청을 api로
  retrofit: ^3.0.1

  #훅 위젯
  flutter_hooks: ^0.18.3

  #이미지 캐싱
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: 3.0.1+1
  floor_generator: 1.2.0
  build_runner: 2.1.2

flutter:


  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
